#!/usr/bin/env bash
# setup-agent-vm.sh
# Run once on the agent VM (192.168.2.132) after Ubuntu is provisioned.
#
# Bootstrap — this script must be downloaded before the repo exists.
# Grab it directly from GitHub:
#
#   curl -fsSL https://raw.githubusercontent.com/jswineinger/simple-agent-mcp/main/scripts/setup-agent-vm.sh \
#     -o setup-agent-vm.sh && bash setup-agent-vm.sh
#
# What this does:
#   1. Install system packages
#   2. Clone the repo (public repo, plain HTTPS, no auth needed)
#   3. Create Python venv and install dependencies
#   4. Set up agent.env, including the mcp-server MCP_AUTH_TOKEN (paste the
#      value generated by setup-mcphost.sh)
#   5. Install and enable the systemd service
#
# Run this as the regular (non-root) user you want the service to run as —
# sudo is invoked only for the specific steps that need it (packages,
# systemd). INSTALL_USER/INSTALL_HOME default to whoever runs this script;
# override them (e.g. `INSTALL_USER=svc INSTALL_HOME=/home/svc bash ...`)
# if you want the service to run as a different, already-existing user.

set -euo pipefail

GITHUB_USER="jswineinger"
GITHUB_REPO="simple-agent-mcp"                # actual GitHub repo slug
LOCAL_DIR_NAME="mcp-lab"                      # local clone dir name

INSTALL_USER="${INSTALL_USER:-$(whoami)}"
INSTALL_HOME="${INSTALL_HOME:-$HOME}"

REPO_DIR="${INSTALL_HOME}/${LOCAL_DIR_NAME}"
AGENT_DIR="${REPO_DIR}/agent"
MCPHOST="192.168.37.6"

echo "=== MCP Lab — Agent VM Setup ==="
echo "  Installing as: ${INSTALL_USER} (home: ${INSTALL_HOME})"
echo ""

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
echo "[1/5] Installing system packages..."
sudo apt-get update -q
sudo apt-get install -y python3 python3-pip python3-venv git curl -q
echo "  Done."

# ---------------------------------------------------------------------------
# 2. Clone the repo
# ---------------------------------------------------------------------------
echo "[2/5] Cloning ${GITHUB_USER}/${GITHUB_REPO}..."
if [ -d "${REPO_DIR}" ]; then
    echo "  Repo already exists — pulling latest..."
    git -C "${REPO_DIR}" pull
else
    git clone "https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git" "${REPO_DIR}"
    echo "  Cloned to ${REPO_DIR}"
fi

# ---------------------------------------------------------------------------
# 3. Python venv
# ---------------------------------------------------------------------------
echo "[3/5] Creating Python venv..."
python3 -m venv "${AGENT_DIR}/venv"
"${AGENT_DIR}/venv/bin/pip" install --upgrade pip -q
"${AGENT_DIR}/venv/bin/pip" install -r "${AGENT_DIR}/requirements.txt" -q
echo "  Venv ready."

# ---------------------------------------------------------------------------
# 4. agent.env — including the mcp-server MCP_AUTH_TOKEN
# ---------------------------------------------------------------------------
echo "[4/5] Setting up agent.env..."
if [ ! -f "${AGENT_DIR}/agent.env" ]; then
    cp "${AGENT_DIR}/agent.env.example" "${AGENT_DIR}/agent.env"
    echo "  Created agent.env from example."
else
    echo "  agent.env already exists — leaving MCPSERVER_IP/MCP_AUTH_TOKEN as-is."
fi

echo ""
echo "  The mcp-server (${MCPHOST}) requires a bearer token on every"
echo "  request — the same value printed by setup-mcphost.sh's step [4/5]."
echo ""
read -rp "  Paste that MCP_AUTH_TOKEN value here (blank = edit agent.env manually later): " MCP_TOKEN
if [ -n "${MCP_TOKEN}" ]; then
    sed -i "s|^MCP_AUTH_TOKEN=.*|MCP_AUTH_TOKEN=${MCP_TOKEN}|" "${AGENT_DIR}/agent.env"
    echo "  MCP_AUTH_TOKEN set in agent.env."
else
    echo "  Skipped — set MCP_AUTH_TOKEN in ${AGENT_DIR}/agent.env before starting."
fi
echo "  Review the rest of agent.env if needed: ${AGENT_DIR}/agent.env"
echo "  (If mcp-server or Ollama live on a different host than this box,"
echo "  also set MCPSERVER_IP / OLLAMA_URL in agent.env — see its"
echo "  Topology comment.)"

# ---------------------------------------------------------------------------
# 5. Systemd service
# ---------------------------------------------------------------------------
echo "[5/5] Installing systemd service..."
sed -e "s|__INSTALL_USER__|${INSTALL_USER}|g" -e "s|__INSTALL_HOME__|${INSTALL_HOME}|g" \
    "${AGENT_DIR}/mcp-agent.service" | sudo tee /etc/systemd/system/mcp-agent.service > /dev/null
sudo systemctl daemon-reload
sudo systemctl enable mcp-agent.service
echo "  Service enabled."

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "=== Setup complete ==="
echo ""
echo "  Start  : sudo systemctl start mcp-agent"
echo "  Status : sudo systemctl status mcp-agent"
echo "  Logs   : sudo journalctl -u mcp-agent -f"
echo "  UI     : http://192.168.2.132:8000"
echo ""
echo "  NOTE: Run setup-mcphost.sh on mcp-server before starting the agent."
