#!/usr/bin/env bash
# setup-agent-vm.sh
# Run once on the agent VM (192.168.2.132) after Ubuntu is provisioned.
#
# Bootstrap — this script must be downloaded before the repo exists.
# Grab it directly from GitHub:
#
#   curl -fsSL https://raw.githubusercontent.com/jswineinger/simple-agent-mcp/main/scripts/setup-agent-vm.sh \
#     -o setup-agent-vm.sh && bash setup-agent-vm.sh
#
# What this does:
#   1. Install system packages
#   2. Generate a GitHub SSH deploy key and wait for you to add it
#   3. Clone the repo
#   4. Create Python venv and install dependencies
#   5. Set up agent.env, including the mcp-server MCP_AUTH_TOKEN (paste the
#      value generated by setup-mcphost.sh)
#   6. Install and enable the systemd service

set -euo pipefail

GITHUB_USER="jswineinger"
GITHUB_REPO="simple-agent-mcp"                # actual GitHub repo slug
LOCAL_DIR_NAME="mcp-lab"                      # local clone dir name — kept
                                               # short; must match the paths
                                               # baked into *.service files
REPO_DIR="/home/labadmin/${LOCAL_DIR_NAME}"
AGENT_DIR="${REPO_DIR}/agent"
GITHUB_KEY="/home/labadmin/.ssh/id_ed25519_github"
MCPHOST="192.168.37.6"

echo "=== MCP Lab — Agent VM Setup ==="
echo ""

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
echo "[1/6] Installing system packages..."
sudo apt-get update -q
sudo apt-get install -y python3 python3-pip python3-venv git openssh-client curl -q
echo "  Done."

# ---------------------------------------------------------------------------
# 2. GitHub SSH deploy key
# ---------------------------------------------------------------------------
echo "[2/6] GitHub SSH key setup..."
mkdir -p /home/labadmin/.ssh
chmod 700 /home/labadmin/.ssh

if [ ! -f "${GITHUB_KEY}" ]; then
    echo "  Generating GitHub deploy key..."
    ssh-keygen -t ed25519 -f "${GITHUB_KEY}" -N "" \
        -C "agent@192.168.2.132-github"
    echo ""
    echo "  ╔══════════════════════════════════════════════════════════════╗"
    echo "  ║  ACTION REQUIRED — Add this deploy key to GitHub            ║"
    echo "  ╚══════════════════════════════════════════════════════════════╝"
    echo ""
    echo "  1. Copy the public key below"
    echo "  2. Go to: https://github.com/${GITHUB_USER}/${GITHUB_REPO}/settings/keys"
    echo "  3. Click 'Add deploy key'"
    echo "  4. Title: agent-vm  |  Key: (paste below)  |  Allow write: NO"
    echo ""
    echo "  ── PUBLIC KEY ──────────────────────────────────────────────────"
    cat "${GITHUB_KEY}.pub"
    echo "  ────────────────────────────────────────────────────────────────"
    echo ""
    read -rp "  Press Enter once the deploy key is saved in GitHub..."
else
    echo "  GitHub key already exists at ${GITHUB_KEY}"
fi

# Configure SSH to use this key for github.com
SSH_CONFIG="/home/labadmin/.ssh/config"
if ! grep -q "Host github.com" "${SSH_CONFIG}" 2>/dev/null; then
    cat >> "${SSH_CONFIG}" <<EOF

Host github.com
    HostName github.com
    User git
    IdentityFile ${GITHUB_KEY}
    StrictHostKeyChecking no
EOF
    chmod 600 "${SSH_CONFIG}"
    echo "  SSH config updated for github.com"
fi

# Test GitHub connectivity
echo "  Testing GitHub SSH access..."
if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
       -i "${GITHUB_KEY}" -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
    echo "  GitHub SSH: OK"
else
    echo "  WARNING: GitHub SSH test inconclusive — proceeding anyway."
    echo "  If clone fails, verify the deploy key is saved in GitHub."
fi

# ---------------------------------------------------------------------------
# 3. Clone the repo
# ---------------------------------------------------------------------------
echo "[3/6] Cloning ${GITHUB_USER}/${GITHUB_REPO}..."
if [ -d "${REPO_DIR}" ]; then
    echo "  Repo already exists — pulling latest..."
    git -C "${REPO_DIR}" pull
else
    GIT_SSH_COMMAND="ssh -i ${GITHUB_KEY} -o StrictHostKeyChecking=no" \
        git clone "git@github.com:${GITHUB_USER}/${GITHUB_REPO}.git" "${REPO_DIR}"
    echo "  Cloned to ${REPO_DIR}"
fi

# ---------------------------------------------------------------------------
# 4. Python venv
# ---------------------------------------------------------------------------
echo "[4/6] Creating Python venv..."
python3 -m venv "${AGENT_DIR}/venv"
"${AGENT_DIR}/venv/bin/pip" install --upgrade pip -q
"${AGENT_DIR}/venv/bin/pip" install -r "${AGENT_DIR}/requirements.txt" -q
echo "  Venv ready."

# ---------------------------------------------------------------------------
# 5. agent.env — including the mcp-server MCP_AUTH_TOKEN
# ---------------------------------------------------------------------------
echo "[5/6] Setting up agent.env..."
if [ ! -f "${AGENT_DIR}/agent.env" ]; then
    cp "${AGENT_DIR}/agent.env.example" "${AGENT_DIR}/agent.env"
    echo "  Created agent.env from example."
else
    echo "  agent.env already exists — leaving MCPSERVER_IP/MCP_AUTH_TOKEN as-is."
fi

echo ""
echo "  The mcp-server (${MCPHOST}) requires a bearer token on every"
echo "  request — the same value printed by setup-mcphost.sh's step [5/6]."
echo ""
read -rp "  Paste that MCP_AUTH_TOKEN value here (blank = edit agent.env manually later): " MCP_TOKEN
if [ -n "${MCP_TOKEN}" ]; then
    sed -i "s|^MCP_AUTH_TOKEN=.*|MCP_AUTH_TOKEN=${MCP_TOKEN}|" "${AGENT_DIR}/agent.env"
    echo "  MCP_AUTH_TOKEN set in agent.env."
else
    echo "  Skipped — set MCP_AUTH_TOKEN in ${AGENT_DIR}/agent.env before starting."
fi
echo "  Review the rest of agent.env if needed: ${AGENT_DIR}/agent.env"
echo "  (If mcp-server or Ollama live on a different host than this box,"
echo "  also set MCPSERVER_IP / OLLAMA_URL in agent.env — see its"
echo "  Topology comment.)"

# ---------------------------------------------------------------------------
# 6. Systemd service
# ---------------------------------------------------------------------------
echo "[6/6] Installing systemd service..."
sudo cp "${AGENT_DIR}/mcp-agent.service" /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable mcp-agent.service
echo "  Service enabled."

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "=== Setup complete ==="
echo ""
echo "  Start  : sudo systemctl start mcp-agent"
echo "  Status : sudo systemctl status mcp-agent"
echo "  Logs   : sudo journalctl -u mcp-agent -f"
echo "  UI     : http://192.168.2.132:8000"
echo ""
echo "  NOTE: Run setup-mcphost.sh on mcp-server before starting the agent."
