#!/usr/bin/env bash
# setup-chatbot-vm.sh
# Run once on the chatbot VM (192.168.2.132) after Ubuntu is provisioned.
#
# Bootstrap — this script must be downloaded before the repo exists.
# Grab it directly from GitHub:
#
#   curl -fsSL https://raw.githubusercontent.com/jswineinger/mcp-lab/main/scripts/setup-chatbot-vm.sh \
#     -o setup-chatbot-vm.sh && bash setup-chatbot-vm.sh
#
# What this does:
#   1. Install system packages
#   2. Generate a GitHub SSH deploy key and wait for you to add it
#   3. Clone the mcp-lab repo
#   4. Create Python venv and install dependencies
#   5. Set up chatbot.env, including the mcphost MCP_AUTH_TOKEN (paste the
#      value generated by setup-mcphost.sh)
#   6. Install and enable the systemd service

set -euo pipefail

GITHUB_USER="jswineinger"
REPO_NAME="mcp-lab"
REPO_DIR="/home/mcpsvc/${REPO_NAME}"
CHATBOT_DIR="${REPO_DIR}/chatbot"
GITHUB_KEY="/home/mcpsvc/.ssh/id_ed25519_github"
MCPHOST="192.168.37.6"

echo "=== MCP Lab — Chatbot VM Setup ==="
echo ""

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
echo "[1/7] Installing system packages..."
sudo apt-get update -q
sudo apt-get install -y python3 python3-pip python3-venv git openssh-client curl -q
echo "  Done."

# ---------------------------------------------------------------------------
# 2. GitHub SSH deploy key
# ---------------------------------------------------------------------------
echo "[2/7] GitHub SSH key setup..."
mkdir -p /home/mcpsvc/.ssh
chmod 700 /home/mcpsvc/.ssh

if [ ! -f "${GITHUB_KEY}" ]; then
    echo "  Generating GitHub deploy key..."
    ssh-keygen -t ed25519 -f "${GITHUB_KEY}" -N "" \
        -C "chatbot@192.168.2.132-github"
    echo ""
    echo "  ╔══════════════════════════════════════════════════════════════╗"
    echo "  ║  ACTION REQUIRED — Add this deploy key to GitHub            ║"
    echo "  ╚══════════════════════════════════════════════════════════════╝"
    echo ""
    echo "  1. Copy the public key below"
    echo "  2. Go to: https://github.com/${GITHUB_USER}/${REPO_NAME}/settings/keys"
    echo "  3. Click 'Add deploy key'"
    echo "  4. Title: chatbot-vm  |  Key: (paste below)  |  Allow write: NO"
    echo ""
    echo "  ── PUBLIC KEY ──────────────────────────────────────────────────"
    cat "${GITHUB_KEY}.pub"
    echo "  ────────────────────────────────────────────────────────────────"
    echo ""
    read -rp "  Press Enter once the deploy key is saved in GitHub..."
else
    echo "  GitHub key already exists at ${GITHUB_KEY}"
fi

# Configure SSH to use this key for github.com
SSH_CONFIG="/home/mcpsvc/.ssh/config"
if ! grep -q "Host github.com" "${SSH_CONFIG}" 2>/dev/null; then
    cat >> "${SSH_CONFIG}" <<EOF

Host github.com
    HostName github.com
    User git
    IdentityFile ${GITHUB_KEY}
    StrictHostKeyChecking no
EOF
    chmod 600 "${SSH_CONFIG}"
    echo "  SSH config updated for github.com"
fi

# Test GitHub connectivity
echo "  Testing GitHub SSH access..."
if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
       -i "${GITHUB_KEY}" -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
    echo "  GitHub SSH: OK"
else
    echo "  WARNING: GitHub SSH test inconclusive — proceeding anyway."
    echo "  If clone fails, verify the deploy key is saved in GitHub."
fi

# ---------------------------------------------------------------------------
# 3. Clone the repo
# ---------------------------------------------------------------------------
echo "[3/7] Cloning ${GITHUB_USER}/${REPO_NAME}..."
if [ -d "${REPO_DIR}" ]; then
    echo "  Repo already exists — pulling latest..."
    git -C "${REPO_DIR}" pull
else
    GIT_SSH_COMMAND="ssh -i ${GITHUB_KEY} -o StrictHostKeyChecking=no" \
        git clone "git@github.com:${GITHUB_USER}/${REPO_NAME}.git" "${REPO_DIR}"
    echo "  Cloned to ${REPO_DIR}"
fi

# ---------------------------------------------------------------------------
# 4. Python venv
# ---------------------------------------------------------------------------
echo "[4/7] Creating Python venv..."
python3 -m venv "${CHATBOT_DIR}/venv"
"${CHATBOT_DIR}/venv/bin/pip" install --upgrade pip -q
"${CHATBOT_DIR}/venv/bin/pip" install -r "${CHATBOT_DIR}/requirements.txt" -q
echo "  Venv ready."

# ---------------------------------------------------------------------------
# 5. chatbot.env — including the mcphost MCP_AUTH_TOKEN
# ---------------------------------------------------------------------------
echo "[5/6] Setting up chatbot.env..."
if [ ! -f "${CHATBOT_DIR}/chatbot.env" ]; then
    cp "${CHATBOT_DIR}/chatbot.env.example" "${CHATBOT_DIR}/chatbot.env"
    echo "  Created chatbot.env from example."
else
    echo "  chatbot.env already exists — leaving MCP_SERVER_URL/MCP_AUTH_TOKEN as-is."
fi

echo ""
echo "  mcphost's MCP server (${MCPHOST}) requires a bearer token on every"
echo "  request — the same value printed by setup-mcphost.sh's step [5/6]."
echo ""
read -rp "  Paste that MCP_AUTH_TOKEN value here (blank = edit chatbot.env manually later): " MCP_TOKEN
if [ -n "${MCP_TOKEN}" ]; then
    sed -i "s|^MCP_AUTH_TOKEN=.*|MCP_AUTH_TOKEN=${MCP_TOKEN}|" "${CHATBOT_DIR}/chatbot.env"
    echo "  MCP_AUTH_TOKEN set in chatbot.env."
else
    echo "  Skipped — set MCP_AUTH_TOKEN in ${CHATBOT_DIR}/chatbot.env before starting."
fi
echo "  Review the rest of chatbot.env if needed: ${CHATBOT_DIR}/chatbot.env"

# ---------------------------------------------------------------------------
# 6. Systemd service
# ---------------------------------------------------------------------------
echo "[6/6] Installing systemd service..."
sudo cp "${CHATBOT_DIR}/mcp-chatbot.service" /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable mcp-chatbot.service
echo "  Service enabled."

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "=== Setup complete ==="
echo ""
echo "  Start  : sudo systemctl start mcp-chatbot"
echo "  Status : sudo systemctl status mcp-chatbot"
echo "  Logs   : sudo journalctl -u mcp-chatbot -f"
echo "  UI     : http://192.168.2.132:8000"
echo ""
echo "  NOTE: Run setup-mcphost.sh on mcphost before starting the chatbot."
